# Generated by Django 4.1.2 on 2022-10-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_alter_faculty_options_alter_moduleelement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('name', 'faculty'), name='unique_module_per_faculty'),
        ),
        migrations.AddConstraint(
            model_name='moduleelement',
            constraint=models.UniqueConstraint(fields=('name', 'module'), name='unique_element_per_module'),
        ),
    ]
