# Generated by Django 4.1.2 on 2022-10-29 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0003_alter_faculty_options_alter_moduleelement_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('start_at', models.TimeField(verbose_name='starts at')),
                ('end_at', models.TimeField(verbose_name='ends at')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.moduleelement', verbose_name='element')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.UniqueConstraint(fields=('element', 'date', 'start_at'), name='one_session_starts_at_a_time'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(check=models.Q(('end_at__gt', models.F('start_at'))), name='check_start_time'),
        ),
    ]
