# Generated by Django 4.1.2 on 2022-10-29 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justified', models.BooleanField(default=False, verbose_name='justified')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.studysession', verbose_name='session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='absence',
            constraint=models.UniqueConstraint(fields=('session', 'student'), name='UNIQUE_session_student'),
        ),
    ]
